name: example
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  dart_holodex_api:
    path: '../'
  dotenv: ^4.1.0

dev_dependencies:
  lints: ^2.0.1
