name: dart_holodex_api
description: A Dart wrapper for Holodex API v2. Holodex is a website dedicated
  towards your favorite vtubers, with features like clips management, and
  music-centric playback.
version: 1.0.0+5
homepage: https://github.com/getBoolean/dart_holodex_api
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ">=0.13.4 <2.0.0"
  intl: ">=0.17.0 <0.19.0"
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  dotenv: ^4.1.0
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  lints: ^2.0.1
  test: ^1.16.0
