name: dart_holodex_api
description: A Dart wrapper for Holodex API v2. Holodex is a website dedicated towards your favorite vtubers, with features like clips management, and music-centric playback.
version: 0.3.0
homepage: https://github.com/getBoolean/dart_holodex_api
environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
